# need 4 gpus

project: coconut-VLLR-mixedc
save_path: checkpoints
name: gsm-coconut-VLLR5-mixedc-nostartmarker

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False
no_bot_tokens : True

c_thought: 6
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: True
termination_gamma: 1

debug: False
bf16: True
save_only_improve: False
model_id: Qwen/Qwen2.5-1.5B
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
# load_model_path: checkpoints/gsm-cot-VLLR/checkpoint_5
load_model_path: checkpoints/gsm-coconut-VLLR5-mixedc-nostartmarker/checkpoint_2_260210_122025.pt     # starts counting at 1

resume: 2     # starting epoch, starts counting at 0. If need to start at epoch 6, enter 6.     # resume at 13 next time
reset_optimizer: False
num_epochs: 10
batch_size_training: 4
gradient_accumulation_steps: 8
lr: !!float "2.5e-5"
weight_decay: 0.01
uniform_prob: 1.0               # reset to 0.0 next round
seed: 42

sdpa_attention: True
grad_checkpointing: False